#!/bin/bash


_get_repolink () {
    local regex
    local rlink
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "goodcat" ]]
    then
        rlink=`echo "aHR0cHM6Ly9naXRodWIuY29tL3NhbmR5MTcwOS9jYXR1c2VyYm90" | base64 -d`
    elif [[ $UPSTREAM_REPO == "badcat" ]]
    then
        rlink=`echo "aHR0cHM6Ly9naXRodWIuY29tL0ppc2FuMDkvY2F0dXNlcmJvdA==" | base64 -d`
    elif [[ $UPSTREAM_REPO == "arabiccat" ]]
    then
        rlink=`echo "aHR0cHM6Ly9naXRodWIuY29tL0FOTDBLRS9jYXR1c2VyYm90" | base64 -d`
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        rlink=`echo "${UPSTREAM_REPO}"`
    else
        rlink=`echo "aHR0cHM6Ly9naXRodWIuY29tL3NhbmR5MTcwOS9jYXR1c2VyYm90" | base64 -d`
    fi
    echo "$rlink"
}


_run_python_code() {
    python3${pVer%.*} -c "$1"
}

_run_mybotdeploy_git() {
    $(_run_python_code 'from git import Repo
import sys

OFFICIAL_UPSTREAM_REPO = "https://github.com/madboy482/MyBotDeploy"
ACTIVE_BRANCH_NAME = "master"

repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_run_mybot_git() {
    local repolink=$(_get_repolink)
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO="'$repolink'"
ACTIVE_BRANCH_NAME = "'$UPSTREAM_REPO_BRANCH'" or "master"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_set_bot () {
    local zippath
    zippath="mybot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_ziplink) -O "$zippath"
    echo "  Unpacking Data ..."
    MYPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    _run_mybotdeploy_git
    cd $MYPATH
    _run_mybot_git
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    chmod -R 755 bin
    echo "    Starting MyBot    "
    echo "
                        +-+ +-+   +-+ +-+ +-+
                        |M| |Y|   |B| |O| |T|
                        +-+ +-+   +-+ +-+ +-+
    "

    echo "
                     +-+ +-+ +-+ +-+ +-+ +-+ +-+
                     |U| |S| |E| |R| |B| |O| |T| 
                     +-+ +-+ +-+ +-+ +-+ +-+ +-+
    "
    python3 -m userbot
}

_set_bot
